# Open Grant Proposal

* **Project:** Coinversation Protocol
* **Proposer:** [coin-pro](https://github.com/coin-pro)
* **Payment Address:** 3FX6TD7Qm255foMg7xZStZNAfpLvDai5P8

## Project Overview :page_facing_up: 
Coinversation Protocol is an open financial platform integrating stablecoin, synthetic asset issuance, collateral lending, decentralized contract exchange and Polkadot bridge.  Coinversation Stablecoin is a very important part of it.  Coinversation is committed to making breakthrough contributions to the stablecoin and DeFi in the Polkadot ecosystem.

### Overview

The stablecoin created by Coinversation Protocol is decentralized, multi-asset collateralized, supports cross-chain, and supports real-world asset access through Polkadot bridge. The biggest difference between it and the past decentralized stablecoins is that there are no stability fees or interest, but stablecoins are issued in a synthetic asset collateral pool. Therefore, the cost that users pay to generate Coinversation Stablecoin (cUSD) through collateral is determined by the relative change of all synthetic assets in the entire system, rather than artificial regulations in previous decentralized stablecoins (e.g. Dai). This cost is more market-oriented, and at the same time it is equivalent to the inflation rate of stablecoin to world assets.  In general, the stable currency cUSD and the synthetic asset issuance and contract exchanges in the Coinversation Protocol constitute a complete Defi system in the Polkadot ecosystem. In addition, we can access alliance chains such as AntChain and HyperChain through Coinversation's own bridge to realize access to various real-world assets. This will not only enrich the collateral for this project, but also enrich the range of assets in the entire Polkadot ecosystem through cross-chain.

### Project Details 
The main functional modules of the entire system include: Polkadot bridge, forging synthetic assets(MintC), DEX, collateral pools, fee pools, oracles, and liquidity mining. 

![img](http://coinversation.cn/static/media/ecosystem.abc42525.svg)

#### Polkadot Bridge
This bridge connect several alliance chains, such as AntChian and HyperChain, into Coinversation Protocol and Polkadot ecosystem. So assets on those chains can be used as collateral to issue stablecoin and synthetic assets. Meanwhile, Coinversation Stablecoin can also provide liquidity for those assets through cUSD lending.

#### Forging Synthetic Assets(MintC)

The synthetic assets issued by the entire system are all produced by users staking certain collateral. The initial collateral includes CTO and DOT, and the collateralization ratio is 800% and 500% respectively. In the future, the collateral and collateralization ratio can be adjusted through community governance. When users stake collaterals and forge synthetic assets, corresponding debts are generated. When the user wants to unlock the collateral, he must repay the debt, that is, destroy the previously generated synthetic assets.

#### cUSD

At present, it is stipulated that the assets synthesized by direct staking of collateral are the stablecoin cUSD. That is, after users stake the CTO or DOT, the directly generated synthetic asset is cUSD, while other synthetic assets need to be converted by the user through contract trading in DEX. The price of cUSD is always defined as $1 throughout the system. All cUSD generated by all users is the total liability of the entire system, priced in cUSD.

Through contract trading, cUSD can be converted into any synthetic assets supported by the system, such as cBTC, cETH, and even cAAPL, cXAU linked to traditional assets such as stocks and gold, and supports long or short. The types of synthetic assets can be added by community governance. It should be noted that if the user simply holds cUSD after minting, it is equivalent to automatically shorting all other assets in the system.

#### DEX

It is an exchange that provides conversion of different synthetic assets and contract trading. Due to the design characteristics of CP, this DEX does not require a counterparty, and there is no issue of transaction depth. 

#### Collateral Pool

The collateral pool is the sum of synthetic assets generated by all users, and is priced in cUSD. According to the amounts of synthetic assets generated by each user, the debt pool also records the proportion of each user's debt. Whenever a new synthetic asset is generated, the debt ratio of the system must be recalculated. 

#### Fee Pool

Users trading or converting synthetic assets on the DEX will incur transaction fees. The fee ratio is tentatively set at 0.3%, and these fees all enter the fee pool. The fee is collected in cUSD, and all the fees are distributed to users in proportion to the debt. The system stipulates that only users whose collateral is the CTO can receive rewards, as an incentive for CTO holders. Because the CTO price fluctuates, it is stipulated that only users who meet the collateralization ratio are eligible to receive rewards.

#### Oracle

Since the price of contract trading needs to be read from outside sources, the oracle is a very critical part of this project. In the initial stage, the system will use the centralized oracles provided by the project team, and in the future, it will introduce more secure decentralized oracles.

#### Liquidity Mining

Liquidity mining is the module of issuing CTO tokens. Users can lock CTO or DOT here to get the rewards of CTO. The proportion of rewards obtained by CTO and DOT is different. It also stipulates that users who lock their tokens for liquidity mining must also put a corresponding proportion of CTO or DOT in the collateral pool to mint synthetic assets, to provide more liquidity for the entire system. 

## Team :busts_in_silhouette:

### Team members
* Qiuye, team leader, PhD in Economics, major in Macroeconomics including currency, finance and exchange rates. Mainly focuses on cryptocurrency and is committed to exploring the fundamental changes that cryptocurrency brings to traditional economic theories.

### Team Website	
* http://coinversation.cn

### Legal Structure 
* Crypto Geeks Capital Ltd.
* No.977 Wenyi West Road, Yongfu Community, Wuchang Street, Yuhang District, Hangzhou City, China

### Team's experience
Founded by a US PhD team, the core members are from first-tier technology companies such as Alibaba, ANT Group, Google. More than 70% of the team members have a Master degree or a PhD degree, and many of them have more than ten years of development experience and are early developers of Ethereum.

### Team Code Repos
* https://github.com/Coinversation

## Development Roadmap :nut_and_bolt: 

This section should break out the development roadmap into a number of milestones. Since the milestones will appear in the grant contract, it helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the contract to ensure that everything has been delivered as expected.

Below we provide an **example roadmap**. In the descriptions it should be clear how the project is related to Substrate and/or Polkadot. We recommend that the scope of the work can fit within a 3 month period and that teams structure their roadmap as 1 month = 1 milestone. 

For each milestone:
* Please be sure to include a specification of your software. Treat it as a contract - the level of detail must be enough to later verify that the software meets the specification.
To assist you in defining it, we created a document with examples for some grant categories [here](../src/grant_guidelines_per_category.md).
* Please include total amount of funding requested per milestone.
* Please note that we require documentation (e.g. tutorials, API specifications, architecture details) in each milestone. This ensures that the code can be widely used by the community.
* Please provide a test suite, comprising unit and integration tests, along with a guide on how to run these.
* Please commit to providing a dockerfiles for the delivery of your project. 
* Please indicate the milestone duration, as well as number of Full-Time Employees working on each milestone, and include the number of days along with their cost per day.

### Overview
* **Total Estimated Duration:** Duration of the whole project
* **Full-time equivalent (FTE):**  Workload of an employed person ([see](https://en.wikipedia.org/wiki/Full-time_equivalent)) 
* **Total Costs:** Amount of Payment in BTC for the whole project. The total amount of funding needs to be below $30k at the time of submission.

### Milestone 1 Example — Implement Substrate Modules 
* **Estimated Duration:** 1 month
* **FTE:**  1
* **Costs:** 0.75 BTC

| Number | Deliverable | Specification |
| ------------- | ------------- | ------------- |
| 0a. | License | Apache 2.0 / MIT / Unlicense |
| 0b. | Documentation | We will provide both inline documentation of the code and a basic tutorial that explains how a user can (for example) spin up one of our Substrate nodes. Once the node is up, it will be possible to send test transactions that will show how the new functionality works. |
| 0c. | Testing Guide | The code will have proper unit-test coverage (e.g. 90%) to ensure functionality and robustness. In the guide we will describe how to run these tests | 
| 1. | Substrate module: X | We will create a Substrate module that will... (Please list the functionality that will be coded for the first milestone) |  
| 2. | Substrate module: Y | We will create a Substrate module that will... |  
| 3. | Substrate module: Z | We will create a Substrate module that will... |  
| 4. | Substrate chain | Modules X, Y & Z of our custom chain will interact in such a way... (Please describe the deliverable here as detailed as possible) |  
| 5. | Docker | We will provide a dockerfile to demonstrate the full functionality of our chain |

### Milestone 2 Example — Additional features
...

## Future Plans
There is still a lot of space for growth in the future, including:

At present, the type of synthetic assets of the project is determined by the project team or community governance. In the future, it is planned to upgrade so that different investors can independently sign any type of contract on this system.

At present, the stablecoin cUSD or other synthetic assets produced by the project are limited to the system. When there are standardized tokens similar to Ethereum ERC-20 on the Polkadot in the future, all synthetic assets of this project can be circulated outside the system in the form of standardized tokens, and even enter other exchanges. Among them, cUSD can become an important stable currency in the Polkadot ecology.

## Additional Information :heavy_plus_sign: 
* Whitepaper: https://github.com/Coinversation/white-paper
