# This is a basic workflow to help you get started with Actions

name: tidy-check

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  pull_request:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ github.event.pull_request.commits_url }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get commit count
        run: echo "::set-output name=count::$(curl ${{ github.event.pull_request.commits_url }} | jq length)"
        id: commit_count
      - name: Request one commit
        if: ${{ steps.commit_count.outputs.count != 1 }}
        uses: thollander/actions-comment-pull-request@master
        with:
          message: > 
            Please double check that your initial PR contains only one commit. Squash if needed.
            <br/><br/> 
            Thank you for keeping our repo tidy!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
