on:
  pull_request_review:
    types: [submitted]

name: Label pull request approvals

jobs:
  labelWhen1Approved:
    name: Awaiting 2 approvals
    runs-on: ubuntu-latest
    steps:
    - name: Two remaining
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "Awaiting 2 approvals"
        REMOVE_LABEL: "ready for review"
    - name: One remaining
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "2"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "Awaiting 1 approval"
        REMOVE_LABEL: "ready for review"
    - name: Label when three approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "3"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "Approved 🚀"
        REMOVE_LABEL: "Awaiting 1 approval"
