name: Update Status Badges
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'docs/polkadot_stack.md'
  workflow_dispatch:

jobs:
  status_badges:
    runs-on: ubuntu-latest
    name: Update status badges
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check and update badges
        uses: lucasvanmol/status-badges@v1
        with:
          path: 'docs/polkadot_stack.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          find-all-links: true